const fs = require('fs');

let data = fs.readFileSync('data/mockData.ts', 'utf8');

const posterUrls = {
  'darkknight': "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Dark_Knight_%282008_film_poster%29.jpg",
  'inception': "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
  'interstellar': "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
  'matrix': "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg",
  'pulpfiction': "https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg",
  'shawshank': "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg",
  'fightclub': "https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg",
  'forrestgump': "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg",
  'godfather': "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
  'lotr1': "https://upload.wikimedia.org/wikipedia/en/9/9d/The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_%282001%29.jpg",
  'avatar': "https://upload.wikimedia.org/wikipedia/en/b/b0/Avatar-Teaser-Poster.jpg",
  'titanic': "https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.jpg",
  'jurassic': "https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg",
  'avengers': "https://upload.wikimedia.org/wikipedia/en/f/f9/TheAvengers2012Poster.jpg",
  'spiderverse': "https://upload.wikimedia.org/wikipedia/en/b/b4/Spider-Man_Into_the_Spider-Verse_poster.jpg",
  'parasite': "https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29_poster.jpg",
  'dune': "https://upload.wikimedia.org/wikipedia/en/8/8e/Dune_%28novel%29.jpg",
  'topgun': "https://upload.wikimedia.org/wikipedia/en/1/13/Top_Gun_Maverick_Poster.jpg",
  'eeaao': "https://upload.wikimedia.org/wikipedia/en/1/1e/Everything_Everywhere_All_at_Once.jpg",
  'batman': "https://upload.wikimedia.org/wikipedia/en/f/ff/The_Batman_%282022_film%29_poster.jpg",
  'blackpanther': "https://upload.wikimedia.org/wikipedia/en/0/0c/Black_Panther_film_poster.jpg",
  'madmax': "https://upload.wikimedia.org/wikipedia/en/6/6e/Mad_Max_Fury_Road.jpg",
  'whiplash': "https://upload.wikimedia.org/wikipedia/en/0/01/Whiplash_poster.jpg",
  'revenant': "https://upload.wikimedia.org/wikipedia/en/6/68/The_Revenant_%282015_film%29_poster.jpg",
  'lalaland': "https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29_poster.jpg",
  'getout': "https://upload.wikimedia.org/wikipedia/en/a/a3/Get_Out_poster.png",
  'socialnetwork': "https://upload.wikimedia.org/wikipedia/en/8/8c/The_Social_Network_film_poster.png",
  'bladerunner': "https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_poster.png",
  'budapest': "https://upload.wikimedia.org/wikipedia/en/a/a6/The_Grand_Budapest_Hotel_poster.jpg",
  'johnwick': "https://upload.wikimedia.org/wikipedia/en/9/98/John_Wick_TeaserPoster.jpg",
  'prestige': "https://upload.wikimedia.org/wikipedia/en/d/d2/Prestige_poster.jpg",
  'gladiator': "https://upload.wikimedia.org/wikipedia/en/8/8a/Gladiator_ver1.jpg",
  'departed': "https://upload.wikimedia.org/wikipedia/en/5/50/Departed234.jpg",
  'lionking': "https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg",
  'goodfellas': "https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg",
  'silence': "https://upload.wikimedia.org/wikipedia/en/8/86/The_Silence_of_the_Lambs_poster.jpg",
  'savingryan': "https://upload.wikimedia.org/wikipedia/en/a/ac/Saving_Private_Ryan_poster.jpg",
  'greenmile': "https://upload.wikimedia.org/wikipedia/en/c/ce/Green_mile.jpg",
  'sixthsense': "https://upload.wikimedia.org/wikipedia/en/a/a4/The_Sixth_Sense_poster.png",
  'terminator': "https://upload.wikimedia.org/wikipedia/en/7/70/Terminator1984movieposter.jpg",
  'backfuture': "https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg",
  'shining': "https://upload.wikimedia.org/wikipedia/en/2/25/The_Shining_poster.jpg",
  'alien': "https://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg",
  'exorcist': "https://upload.wikimedia.org/wikipedia/en/2/2b/The_Exorcist_poster.jpg",
  'casablanca': "https://upload.wikimedia.org/wikipedia/commons/b/b3/CasablancaPoster-Gold.jpg",
  'psycho': "https://upload.wikimedia.org/wikipedia/en/b/b9/Psycho_%281960%29.jpg",
  'citizen': "https://upload.wikimedia.org/wikipedia/en/0/0c/Citizen_Kane_poster%2C_1941.jpg",
  'wizard': "https://upload.wikimedia.org/wikipedia/commons/7/7c/Wizard_of_oz_poster_1939.jpg",
  'gonewind': "https://upload.wikimedia.org/wikipedia/commons/2/27/Poster_-_Gone_With_the_Wind_01.jpg",
  'schindler': "https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg",
};

const trailerUrls = {
  '1': "https://www.youtube.com/watch?v=EXeTwQWrcwY",
  '2': "https://www.youtube.com/watch?v=YoHD9XEInc0",
  '3': "https://www.youtube.com/watch?v=zSWdZVtXT7E",
  '4': "https://www.youtube.com/watch?v=vKQi3bBA1y8",
  '5': "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
  '6': "https://www.youtube.com/watch?v=6hB3S9bIaco",
  '7': "https://www.youtube.com/watch?v=BdJKm16Co6M",
  '8': "https://www.youtube.com/watch?v=bLvqoHBptjg",
  '9': "https://www.youtube.com/watch?v=sY1S34973zA",
  '10': "https://www.youtube.com/watch?v=V75dMMIW2B4",
  '11': "https://www.youtube.com/watch?v=5PSNL1qE6VY",
  '12': "https://www.youtube.com/watch?v=kVrqfYjkTdQ",
  '13': "https://www.youtube.com/watch?v=lc0UehYemQA",
  '14': "https://www.youtube.com/watch?v=eOrNdBpGMv8",
  '15': "https://www.youtube.com/watch?v=g4Hbz2jLxvQ",
  '16': "https://www.youtube.com/watch?v=5xH0HfJHsaY",
  '17': "https://www.youtube.com/watch?v=n9xhJrPXop4",
  '18': "https://www.youtube.com/watch?v=qSqVVswa420",
  '19': "https://www.youtube.com/watch?v=wxN1T1uxQ2g",
  '20': "https://www.youtube.com/watch?v=mqqft2x_Aa4",
  '21': "https://www.youtube.com/watch?v=xjDjIWPwcPU",
  '22': "https://www.youtube.com/watch?v=hEJnMQG9ev8",
  '23': "https://www.youtube.com/watch?v=7d_jQycdQGo",
  '24': "https://www.youtube.com/watch?v=LoebZZ8K5N0",
  '25': "https://www.youtube.com/watch?v=0pdqf4P9MB8",
  '26': "https://www.youtube.com/watch?v=DzfpyUB60YY",
  '27': "https://www.youtube.com/watch?v=lB95KLmpLR4",
  '28': "https://www.youtube.com/watch?v=gCcx85zbxz4",
  '29': "https://www.youtube.com/watch?v=1Fg5iWmQjwk",
  '30': "https://www.youtube.com/watch?v=2AUmvWm5ZDQ",
  '31': "https://www.youtube.com/watch?v=o4gHCmTQDVI",
  '32': "https://www.youtube.com/watch?v=owK1qxDselE",
  '33': "https://www.youtube.com/watch?v=SGWvwjZ0eDc",
  '34': "https://www.youtube.com/watch?v=4sj1MT05lAA",
  '35': "https://www.youtube.com/watch?v=qo5jJpHtI1Y",
  '36': "https://www.youtube.com/watch?v=W6Mm8Sbe__o",
  '37': "https://www.youtube.com/watch?v=zwhP5b4tD6g",
  '38': "https://www.youtube.com/watch?v=Ki4haFrqSrw",
  '39': "https://www.youtube.com/watch?v=VG9AGf66tXM",
  '40': "https://www.youtube.com/watch?v=k64P4l2Wmeg",
  '41': "https://www.youtube.com/watch?v=qvsgGtivCgs",
  '42': "https://www.youtube.com/watch?v=5Cb3ik6zP2I",
  '43': "https://www.youtube.com/watch?v=LjLamj-b0I8",
  '44': "https://www.youtube.com/watch?v=YDGw1MTEe9k",
  '45': "https://www.youtube.com/watch?v=BkL9l7q362E",
  '46': "https://www.youtube.com/watch?v=NG3-GlvKPcg",
  '47': "https://www.youtube.com/watch?v=8dxh3lwdOFw",
  '48': "https://www.youtube.com/watch?v=hZsd8JjGcko",
  '49': "https://www.youtube.com/watch?v=0X1vW4is9Lc",
  '50': "https://www.youtube.com/watch?v=JdRGC-w9syA",
};

data = data.replace(/getPosterUrl\('([^']+)'\)/g, (match, key) => '"' + posterUrls[key] + '"');
data = data.replace(/getBackdropUrl\('([^']+)'\)/g, (match, key) => '"' + posterUrls[key] + '"');
data = data.replace(/getVideoUrl\('([^']+)'\)/g, (match, key) => '"' + trailerUrls[key] + '"');
data = data.replace(/getThumbnailUrl\('([^']+)'\)/g, (match, key) => '"' + posterUrls[key] + '"');

fs.writeFileSync('data/mockData.ts', data);

console.log('Replaced');